---
version: 2
multicolumn: false
web-width: '300'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/cluster/variance.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/226673/articles/285209/master/folder/figures/cluster"
    url: "/users/226673/articles/285209/master/file/figures/cluster/variance.png"
