---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/cluster/cluster.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/226673/articles/285209/master/file/figures/cluster/cluster.png"
    folder_url: "/users/226673/articles/285209/master/folder/figures/cluster"
