---
version: 2
multicolumn: false
web-width: 200
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/ChemicalSpace/ChemicalSpace.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/226673/articles/285209/master/file/figures/ChemicalSpace/ChemicalSpace.png"
    folder_url: "/users/226673/articles/285209/master/folder/figures/ChemicalSpace"
